### PR TITLE
Add new apiUrlV1 env variable

### PR DESCRIPTION
**Pull request by reqlez**
- Added new apiUrlV1 env variable.
- Set alternativeLogo to false ( otherwise it says testnet on logo when true? )

### CODE REVIEW

**Comment by abchrisxyz** [comment]
Thanks for figuring that out. Can you just leave `alternativeLogo` out of this PR so it doesn't mess with other people's setup out there?

**Comment by reqlez** [comment]
> Thanks for figuring that out. Can you just leave `alternativeLogo` out of this PR so it doesn't mess with other people's setup out there?

Sure. Not really sure the purpose of setting logo to "testnet" when by default the label is set to "Mainnet" but I will modify it :)

**Comment by reqlez** [comment]
Actually... my previous modification fixes: https://github.com/abchrisxyz/ergo-setup/issues/4   again, not sure why you want to remove it.

The label on the right says Mainnet or Testnet why does the logo need to be set to "testnet" ?

For reference, this is how the logo looks when this variable is set to "false" https://ergo-explorer.tosidrop.io

**Comment by abchrisxyz** [comment]
You're right. I tried keeping the default config in line with upstream, but makes sense to set it to false.

**Pull request merged**
